ericnewton76/gmaps-api-net

README.md, src/Google.Maps/GoogleSigned.cs
This will allow the usage of api_key's
=> Allow usage of api_key's

README.md, src/Google.Maps/Google.Maps.csproj, src/Google.Maps/TimeZone/TimeZoneRequest.cs, src/Google.Maps/TimeZone/TimeZoneResponse.cs, src/Google.Maps/TimeZone/TimeZoneService.cs
I have implemented a wrapper for the Google Maps [Time Zone API](https://developers.google.com/maps/documentation/timezone/intro).
I've kept this PR as small as possible, as such it affects no existing source files.
It will merge in cleanly at this stage.
=> Time Zone API

src/Google.Maps/Places/PlacesResult.cs
The place_id is not being returned with the places search. This adds the property so its being serialized and returned.
=> Return the place_id with a places search

src/Google.Maps/Direction/DirectionRequest.cs, src/Google.Maps/TravelMode.cs
This is tested and working. Added "transit" in the transport mode options, as per the latest Google Maps Directions API: https://developers.google.com/maps/documentation/directions/intro#TravelModes
=> Added public transit in travel modes

src/Google.Maps/Google.Maps.csproj, src/Google.Maps/packages.config
The library works fine with the latest Newtonsoft.Json, I suggest upgrading to the newer version.
=> Upgraded Newtonsoft.Json

src/Google.Maps/Direction/DirectionLeg.cs, src/Google.Maps/Direction/DirectionStep.cs, src/Google.Maps/Direction/DirectionTransitDetails.cs, src/Google.Maps/Direction/LineInfo.cs, src/Google.Maps/Direction/Stop.cs, src/Google.Maps/Direction/Time.cs, src/Google.Maps/Direction/TransitAgency .cs, src/Google.Maps/Direction/VehicleInfo.cs
Hi I noticed that Direction was a bit out of date so i created and update some classes in order to be able to retrieve the new information provided by the Google Directions  API.
The changes are:
-Update to DirectionLeg and DirectionStep(only add some atributtes and delete "maneuver" since its not used anymore)
-Add the class required for the new "transit_details"
Im new to this so if ive done anything wrong just comment and ill do it again. Even some advice for the pull, because I dont know if I do it the way its supposed to be done.
Thanks
=> Update For Directions

src/Google.Maps.Test/DistanceMatrix/LiveDistanceMatrixTest.cs, src/Google.Maps.Test/Google.Maps.Test.csproj, src/Google.Maps/DistanceMatrix/DistanceMatrixResponse.cs, src/Google.Maps/DistanceMatrix/DistanceMatrixService.cs, src/Google.Maps/Waypoint.cs
Extended the Waypoint object to meet Google's current documentation and wrote NUnit tests for DistanceMatrixAPI.
=> DistanceMatrix API extended

src/Google.Maps.Test/DistanceMatrix/LiveDistanceMatrixTest.cs, src/Google.Maps.Test/Google.Maps.Test.csproj, src/Google.Maps/DistanceMatrix/DistanceMatrixResponse.cs, src/Google.Maps/DistanceMatrix/DistanceMatrixService.cs, src/Google.Maps/Waypoint.cs
Google does not allow http with authentication (request with key)
Also on my previous pull request I mistakenly changed the Waypoint properties to private (did not notice the default constructor). Changed it back to public.
=> Http Request with key denied fixed

src/Google.Maps/Elevation/ElevationService.cs
Implements Issue #61. Elevation Service is now Https.
=> Issue #61 fix

src/Google.Maps.Test/Direction/DirectionServiceTests.cs, src/Google.Maps.Test/Direction/json_queries/origin=Toront$destination=Montreal.json, src/Google.Maps.Test/Direction/json_queries/origin=Toronto$destination=Montreal.json, src/Google.Maps.Test/Google.Maps.Test.csproj, src/Google.Maps/Direction/DirectionResponse.cs, src/Google.Maps/Direction/GeocodedWaypoint.cs, src/Google.Maps/Google.Maps.csproj, src/Google.Maps/JsonEnumTypeConverter.cs, src/Google.Maps/KeyValue.cs, src/Google.Maps/ServiceResponseStatus.cs
=> Add missing Geocoded Waypoints

src/Google.Maps/DistanceMatrix/DistanceMatrixRequest.cs
Encode special characters in distace matrix addreses
=> Encode special characters

src/Google.Maps.Test/Places/PlacesServiceTests.cs, src/Google.Maps/Places/PlacesResponse.cs, src/Google.Maps/Places/TextSearchRequest.cs
Also added PageToken to TextSearchRequest since the API includes it in that type of request also (but not in Radar Search Requests).
=> Add NextPageToken to PlacesResponse as detailed in issue #77.

README.md
I've taken a stab at overhauling the README. I don't think any significant changes to the structure or content have been made since it was first forked from Luis all those years ago!
I know this runs the risk of offending people whose names I've moved / removed, but I've tried to be as thoughtful as possible while trying to clean the document and make it a bit more readable.
I've also taken out the road map section - hope that's OK - I didn't really think that it was an accurate statement, and I could never figure out whether the "WORKING" comments meant it was working or that it wasn't available and was being worked on :)
I don't want to merge this without getting a few thumbs up from the folks who have contributed recently, so @Sheepzez , @frankhommers , @mieliespoor , @ericnewton76 , …
=> chore: overhaul the README

src/Google.Maps.Test/Google.Maps.Test.csproj, src/Google.Maps.Test/Roads/RoadsServiceTests.cs, src/Google.Maps.Test/Roads/SnapToRoadsRequestTests.cs, src/Google.Maps/Google.Maps.csproj, src/Google.Maps/Roads/RoadsService.cs, src/Google.Maps/Roads/SnapToRoadsRequest.cs, src/Google.Maps/Roads/SnapToRoadsResponse.cs, src/Google.Maps/Roads/SnappedPoint.cs, src/Google.Maps/Roads/SnappedPointLocation.cs
Added RoadsService with "Snap to Roads" functionality. Roads API is wider, but I needed this functionality. Unfortunately API key provided in project doesn't allow this (403 forbidden). I am not sure why. I can write tests, but I need working key and confirmation that this has chance to land in main repository.
=> Implemented snap to roads functionality from Roads API

README.md, appveyor.yml, src/Google.Maps.Test/Google.Maps.Test.csproj, src/Google.Maps.Test/StreetView/StreetViewRequestTests.cs, src/Google.Maps.Test/StreetView/StreetView_uribuilding_Tests.cs, src/Google.Maps/Constants.cs, src/Google.Maps/StreetView/StreetViewRequest.cs, src/Google.Maps/StreetView/StreetViewService.cs, src/Samples/SearchAddressMap/App.xaml, src/Samples/SearchAddressMap/App.xaml.cs, src/Samples/SearchAddressMap/SearchAddressMap.csproj, src/Samples/SearchAddressMap/Window1.xaml, src/Samples/SearchAddressMap/Window1.xaml.cs
Adds support for StreetView API.  Closes issue #107
=> Streetviewapi

src/Google.Maps/Direction/DirectionStep.cs
=> added nested Steps property for issue 73

appveyor.yml, src/Google.Maps.Test/Direction/DirectionServiceTests.cs, src/Google.Maps/Common/IServiceResponse.cs, src/Google.Maps/Direction/DirectionResponse.cs, src/Google.Maps/DistanceMatrix/DistanceMatrixResponse.cs, src/Google.Maps/Elevation/ElevationResponse.cs, src/Google.Maps/Geocoding/GeocodeResponse.cs, src/Google.Maps/Places/PlacesResponse.cs, src/Google.Maps/TimeZone/TimeZoneResponse.cs
Merge release to grab hotfix changes
=> Downmerge release into master to collect hotfix changes

README.md
Google has several API's relating to maps - thought this would be helpful to get up and running with the library quicker
=> Update README.md with link to create api key

src/Google.Maps/Internal/StringCaseExtensions.cs, src/Google.Maps/Places/Autocomplete/AutocompleteRequest.cs, src/Google.Maps/Places/PlaceType.cs
Also, support collection type values (cities) and (regions)
This resolves issue #122
=> Correctly translate PlaceType enum to snake_case in the request Uri

src/Google.Maps/Direction/DirectionRequest.cs
Add Waypoint Optimization option to Direction Requests
=> Add Waypoint Optimization option

src/Google.Maps/Geocoding/GeocodingService.cs, src/Google.Maps/Geocoding/IGeocodingService.cs
Added GeocodingService interface in order to be able to mock service. Related to issue #95.
=> Add GeocodingService Interface
